### ISSUE TITLE
Error while 'make'

### ISSUE THREAD

**Issue by teresouza** [ratschlab/rDiff#3]
Hi, I was trying to install rDiff but I keep getting this error while running make:

[...]
gcc -c -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/octave-3.8.2/octave/.. -I/usr/include/octave-3.8.2/octave -I/usr/include/hdf5/serial  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -pthread -fopenmp -g   -I.  liblfev.c -o liblfev.o
liblfev.c: In function ‘getnextdir’:
liblfev.c:4233:3: warning: zero-length gnu_printf format string [-Wformat-zero-length]
   { sprintf(dirnext,"");
   ^
g++ -shared -Wl,-Bsymbolic  -o mexpp.mex  mexpp.o mlfut.o liblocf.o libmut.o libtube.o liblfev.o   -L/usr/lib/x86_64-linux-gnu/octave/3.8.2 -L/usr/lib/x86_64-linux-gnu -loctinterp -loctave -Wl,-Bsymbolic-functions -Wl,-z,relro  
cp mexpp.mex ../mex/
make[1]: Leaving directory '/home/terezinha/Downloads/rDiff/src/locfit/Source'

I used ./configure -i to set up paths and everything seems ok, so what seems to be the problem?
Thanks!

**Comment by vipints** [comment]
what is the underlying operating system here?

**Comment by teresouza** [comment]
Ubuntu 15.04 x64. I also tried to run through galaxy (locally, adding to my tool shed as admin), specifying paths and all in the rdiff_config.sh, but it also ended in an error.
Apparently it cannot start octave - which appears to be the same problem as above since it cannot generate some mex files. This was the last error:

error: get_reads_for_gene: /home/terezinha/shed_tools/toolshed.g2.bx.psu.edu/repos/vipints/rdiff/29a698dc5c7e/rdiff/rDiff/src/tools/read_utils/get_reads.mex: failed to load: libcruft.so: cannot open shared object file: No such file or directory error: ca

This was at the end of the log: 
[...]
starting Octave failed

And I tried several times to re-'make' but after the first failed attempt I get this:
cd rDiff
make
echo Entering ./mex
Entering ./mex
cd mex ; make octave
make[1]: Entering directory '/home/terezinha/Downloads/rDiff/mex'
make[1]: Nothing to be done for 'octave'.
make[1]: Leaving directory '/home/terezinha/Downloads/rDiff/mex'
echo Entering ./src/locfit/Source
Entering ./src/locfit/Source
cd src/locfit/Source ; make octave
make[1]: Entering directory '/home/terezinha/Downloads/rDiff/src/locfit/Source'
make[1]: Nothing to be done for 'octave'.
make[1]: Leaving directory '/home/terezinha/Downloads/rDiff/src/locfit/Source'

So I guess the problem here is octave, then? What should I do?
Thanks!

**Comment by vipints** [comment]
Using the guide https://www.gnu.org/software/octave/doc/interpreter/Compiling-Octave-with-64_002dbit-Indexing.html, we have automated the process of compiling the octave 64bit and you can get it from here: https://github.com/vipints/oqtans/blob/master/oqtans_src/octave-3.6.4_x64.tar.bz2

**Comment by vipints** [comment]
As you saw already this is also nicely documented in #2
