### ISSUE TITLE
rDiff example data is not available on cbio.mskcc.org website

### ISSUE THREAD

**Issue by martinjvickers** [ratschlab/rDiff#6]
The example data is no longer available on the website.

```
wget -c http://cbio.mskcc.org/public/raetschlab/user/drewe/rdiff/example_data.tar.gz
--2017-11-07 12:07:08--  http://cbio.mskcc.org/public/raetschlab/user/drewe/rdiff/example_data.tar.gz
Resolving cbio.mskcc.org (cbio.mskcc.org)... 140.163.254.35
Connecting to cbio.mskcc.org (cbio.mskcc.org)|140.163.254.35|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-11-07 12:07:08 ERROR 404: Not Found.
```

**Comment by AlexWeinreb** [comment]
In `./examples/get_data.sh`, you want to change line 23 from:

    wget -c http://cbio.mskcc.org/public/raetschlab/user/drewe/rdiff/example_data.tar.gz
to:

    wget -c https://public.bmi.inf.ethz.ch/user/drewe/rdiff/data/example_data.tar.gz

The correct links are available on the website in the "publication" tab, but doesn't list all the files needed.

**Comment by philippdre** [comment]
Done.

Thx for letting me know that the paths were outdated.

Best regards,
Philipp

**Comment by martinjvickers** [comment]
Fixed in; https://github.com/ratschlab/rDiff/blob/90fa6cb643a22145f6e06555b2626a2ce14ab111/examples/get_data.sh#L23
